translate: API/01-style-export
svelte-jp/svelte-site-jp pull request #191
Opened 2021-02-10 18:19 UTC by Shunpoco

## 概要
- APIリファレンスの Component Format ~ script/1. `export` creates a component prop までを日本語訳したものを追加します。

close #181, #182

2021-02-10 18:20 UTC, Shunpoco commented on content/docs/ja/01-component-format.ja.md
> +ここで説明されるスクリプト、スタイル、マークアップのいずれもコンポーネントに必須のものではありません。
原文だと `optional` とありますが、直訳して `選択可能です` だと意味が伝わらないかもしれない、と思ったため
`必須ではありません` という表現にしています。
他に良い表現があればぜひご指摘お願いします。

2021-02-11 09:06 UTC, tomoam commented on content/docs/ja/01-component-format.ja.md
> +ここで説明されるスクリプト、スタイル、マークアップのいずれもコンポーネントに必須のものではありません。
「必須ではありません」という表現で良いと思います！

「スクリプト」「スタイル」については、サンプルコードの<script>、<style>に対応しているので、それぞれ「script」「style」に修正して頂けますか。
※ちょうど表記を統一するためのガイドラインと辞書を作成しているところです、まだお見せできなくてすみません！

2021-02-11 09:07 UTC, tomoam commented on content/docs/ja/01-component-format.ja.md
> -
26行目の空行は残して頂けますか！細かくてすみません！

2021-02-11 09:18 UTC, tomoam commented on content/docs/ja/01-component-format.ja.md
> +Svelteでは、 変数の宣言に対して *プロパティ* または *プロップ* を付けるために `export` キーワードを使います。これは、そのコンポーネントの使用者からプロパティが付いた変数にアクセスできることを意味します（より詳しい情報は [属性とプロップ](docs#Attributes_and_props)を見てください）。
prop/propsはVueの日本語ドキュメントに合わせてそのままprops/propにしようと考えております。
また、それがプロパティ(property/properties)を意味することを示したいのでこうしましょう。

` *プロパティ* または *プロップ* `
↓
` *prop*(*プロパティ*) `

2021-02-11 09:18 UTC, tomoam approved these changes

2021-02-11 09:19 UTC, tomoam requested changes
まだレビューは途中です、あとでまた着手します、すみません！

2021-02-11 16:25 UTC, tomoam requested changes
いくつか修正依頼を出しましたが、多くはこちらが辞書を作れていなかったりガイドラインをまだ出せていないためです、申し訳ありません。
まだこちらが方針を示せていないにも関わらず、こうやって時間と労力を割いてくださって本当に感謝しています！

2021-02-11 16:25 UTC, tomoam commented on content/docs/ja/01-component-format.ja.md
> +prop 変数には、初期値を指定することができます。これは、コンポーネントの使用者がコンポーネントのインスタンスが生成される時に、 prop 変数に何も値を渡さない場合（または渡された値の初期値が `undefined` の場合）使用されます。使用者によって prop 変数が消去される場合、その値は初期値ではなく `undefined` になることに注意してください。
下記の通りに変更してください。

```
propはデフォルトの初期値を指定することができます。これはコンポーネントの初期化時にpropが指定されていない場合(または初期値が`undefined`の場合)に使用されます。propを削除すると、その値は初期値ではなく `undefined` になることに注意してください。
```

2021-02-11 16:25 UTC, tomoam commented on content/docs/ja/01-component-format.ja.md
> +ディベロップメントモード（[コンパイラオプション](docs#svelte_compile)を参照）では、 prop 変数に初期値が指定されておらず、使用者も値を渡していない場合警告が出ます。この警告を解消するためには、たとえ　`undefined` であっても初期値を指定してください。
下記のとおりに変更してください。

```
developmentモード（[コンパイラオプション](docs#svelte_compile)を参照）では、デフォルトの初期値が指定されておらず、使用時に値を指定していない場合に警告が表示されます。この警告を解消するためには、たとえ`undefined`であっても初期値を指定してください。
```

2021-02-11 16:25 UTC, tomoam commented on content/docs/ja/01-component-format.ja.md
> +もし `const`、 `class`、 または `function` に `export` を与える場合は、これらはコンポーネントの外からは読み取り専用になりますが、関数の *式* は prop になります。
下記の通りに変更してください。

```
`const`、 `class`、 または `function` をエクスポートする場合、コンポーネントの外からは読み取り専用になります。ただし、関数(function)の *式* は有効な props です。
```

2021-02-11 16:25 UTC, tomoam commented on content/docs/ja/01-component-format.ja.md
> +	// これはpropになります
下記の通りに変更してください。

```
これはpropです
```

2021-02-11 16:25 UTC, tomoam commented on content/docs/ja/01-component-format.ja.md
> +	// これらは読み取り専用になります
下記の通りに変更してください。

```
これらは読み取り専用です
```

2021-02-11 16:25 UTC, tomoam commented on content/docs/ja/01-component-format.ja.md
> +予約語も prop 変数の名前として使用することができます。
下記の通りに変更してください。

```
予約語も prop の名前として使用することができます。
```

2021-02-12 16:11 UTC, Shunpoco commented
ありがとうございます！
こちら、ご指摘の点対応しました。

2021-02-13 04:34 UTC, tomoam approved these changes
OKです！こちらの準備が整っていない中で、いっぱい翻訳してくれてありがとうございます！

2021-02-13 04:34 UTC, merged