add 04-compile-time in Japanese
svelte-jp/svelte-site-jp pull request #195
Opened 2021-02-11 11:01 UTC by myLifeAsaDog

docs の 04-compile-time を全訳しておきました、まだ issue が立っていないのでとりあえず PR だけ立てておきます。

2021-02-11 11:05 UTC, myLifeAsaDog commented on content/docs/ja/04-compile-time.ja.md
> +	* `export_name` は、エクスポートされた場合に使用される名前です。 (`export...as` でない限り、`name` と一致します)
> `export_name` is the name the value is exported as, if it is exported

を直訳すると

> エキスポートネームはエキスポートされるときに、値がエキスポートされる名前です

みたいな回文じみた内容になって全然頭に入ってこないので、

> エクスポートされた場合に使用される名前です

に意訳しました。

2021-02-11 11:12 UTC, myLifeAsaDog commented on content/docs/ja/04-compile-time.ja.md
> +コンパイラの組み込みインスタンスである[estree-walker](https://github.com/Rich-Harris/estree-walker)を使用します。
ここの「ウォーク・ウォーカー」なのですが、どうも AST（抽象構文木）業界では普通に ウォーク と呼称しているらしく、
他に適切な語がないことと、実際に語っているのはASTの walk関数についてで、これを提供しているのも estree-walker であり、
さらに次の段落でも waik や walker という語がつかわれていることから、そのまま「ウォーク・ウォーカー」としました。　

2021-02-11 14:04 UTC, tomoam requested changes
よくこれだけ大量に翻訳してくださいました！流石ですね！

まだ英文自体は見れていないので引き続きレビューを続けますが、空行やご質問があった部分のみ回答しました！

2021-02-11 14:04 UTC, tomoam commented on content/docs/ja/04-compile-time.ja.md
> +コンパイラの組み込みインスタンスである[estree-walker](https://github.com/Rich-Harris/estree-walker)を使用します。
「ウォーク・ウォーカー」で良いと思います！もし訳すとしたら「辿る」とか「探索する」とかですかね。再帰下降構文解析とかでwalkという文字を見る気がします。

2021-02-11 15:15 UTC, myLifeAsaDog commented on content/docs/ja/04-compile-time.ja.md
修正しましたー

2021-02-11 15:16 UTC, myLifeAsaDog commented on content/docs/ja/04-compile-time.ja.md
> -
調整してみましたー

2021-02-12 05:17 UTC, tomoam requested changes
翻訳自体はバッチリだと思います、ありがとうございます！
2箇所だけ記号に関する修正をお願いします！

2021-02-12 05:17 UTC, tomoam commented on content/docs/ja/04-compile-time.ja.md
> +| `loopGuardTimeout` | 0 | `loopGuardTimeout` msを超えてスレッドがブロックされた場合にループを解除するようにSvelteに指示する `数値` です。これは無限ループを防ぐのに便利です。`dev: true` **の場合にのみ利用可能です**
ここの`**`を原文に合わせた位置にできますか？プレビューなどでおかしくなるようだったら今のままで大丈夫です！

```
`dev: true` **の場合にのみ利用可能です**
```
↓
```
** `dev: true` の場合にのみ利用可能です**。
```

2021-02-12 05:17 UTC, tomoam commented on content/docs/ja/04-compile-time.ja.md
> +	* `map` はソースマップに `toString() と `toUrl() の便利なメソッドを追加したものです。
ここ、バッククォートが足りないようです。

```
* `map` はソースマップに `toString() と `toUrl() の便利なメソッドを追加したものです。
```
↓
```
* `map` はソースマップに `toString()` と `toUrl()` の便利なメソッドを追加したものです。
```

2021-02-12 05:31 UTC, myLifeAsaDog commented on content/docs/ja/04-compile-time.ja.md
> +	* `map` はソースマップに `toString() と `toUrl() の便利なメソッドを追加したものです。
修正しましたー

2021-02-12 05:33 UTC, myLifeAsaDog commented on content/docs/ja/04-compile-time.ja.md
> +| `loopGuardTimeout` | 0 | `loopGuardTimeout` msを超えてスレッドがブロックされた場合にループを解除するようにSvelteに指示する `数値` です。これは無限ループを防ぐのに便利です。`dev: true` **の場合にのみ利用可能です**
これ、文の先頭が`スペース`もしくは`バッククォート`だと強調されないみたいなので、ちょっと訳文の方を入れ替えました。

2021-02-12 05:41 UTC, tomoam commented on content/docs/ja/04-compile-time.ja.md
> +| `loopGuardTimeout` | 0 | `loopGuardTimeout` msを超えてスレッドがブロックされた場合にループを解除するようにSvelteに指示する `数値` です。これは無限ループを防ぐのに便利です。`dev: true` **の場合にのみ利用可能です**
そういうことだったんですね、承知しました！

2021-02-12 05:43 UTC, tomoam approved these changes
OKです！ありがとうございます！

2021-02-12 05:43 UTC, merged