translate: [API]01-component-format - <script> - '3. $: marks a state…
svelte-jp/svelte-site-jp pull request #196
Opened 2021-02-11 16:31 UTC by jay-es

`3. $: marks a statement as reactive` 部分を翻訳いたしました。
お手すきの際にレビューお願いします。

close #184

2021-02-11 16:32 UTC, jay-es commented on content/docs/ja/01-component-format.ja.md
↑Diff 切れていますが、他のPRに倣ってタイトル部分はそのままにしています

2021-02-11 16:33 UTC, jay-es commented on content/docs/ja/01-component-format.ja.md
> +トップレベルの（つまりブロック内や関数内でない）ステートメントは `$:` という [JS ラベル構文](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/label) のプレフィックスをつけることでリアクティブにできます。リアクティブステートメントは依存する値が変更されるたび、コンポーネント更新の
statement は「文」だと分かりづらいかと思い「ステートメント」としました

2021-02-11 16:33 UTC, jay-es commented on content/docs/ja/01-component-format.ja.md
> +		console.log(`複数のステートメントをまとめることができます`);
ここも重要な説明なので翻訳してあります

2021-02-11 16:41 UTC, jay-es commented on content/docs/ja/01-component-format.ja.md
> +`$:` のブロック内に直接現れる値だけがリアクティブステートメントの依存関係になります。例えば次のコードで `total` は `x` が変更された時にのみ更新され、`y` では更新されません。
原文は below ですが PC などで見るとコードは下にないので「次の」としました。
（本家にも PR 出してみようと思います）

2021-02-11 16:48 UTC, jay-es commented on content/docs/ja/01-component-format.ja.md
> +		console.log(`現在のタイトルは ${title}`);
この行だけ英語のままだと浮いてしまったので、日本語にしました

2021-02-11 16:50 UTC, jay-es commented on content/docs/ja/01-component-format.ja.md
> +		console.log(`現在のタイトルは ${title}`);
ここは重要な説明だと思ったので翻訳してあります
（2行目だけ英語のままだと浮いてしまったので、合わせて日本語にしました）

2021-02-11 16:55 UTC, jay-es commented on content/docs/ja/01-component-format.ja.md
> +`$:` のブロック内に直接現れる値だけがリアクティブステートメントの依存関係になります。例えば次のコードで `total` は `x` が変更された時にのみ更新され、`y` では更新されません。
`in the code below` 部分ですが、PC などで見るとコードは横にあるので「次の」としました。
（本家にも PR 出してみようと思います）

2021-02-12 05:39 UTC, tomoam requested changes
タイトルの翻訳だけ、お手数ですがお願いいたします！

2021-02-12 05:39 UTC, tomoam commented on content/docs/ja/01-component-format.ja.md
お気遣いありがとうございます！

APIでは一応見出しも翻訳しようと考えています。
（他のPRでやってなかったのは多分レビュー漏れです、すみません。）

なのでここも翻訳をお願いします。
下記のような翻訳でどうでしょうか。

```
`$:`はステートメントがリアクティブであることを示す
```

もちろん、もっと良い日本語訳があれば歓迎します！

2021-02-12 05:39 UTC, tomoam commented on content/docs/ja/01-component-format.ja.md
> +トップレベルの（つまりブロック内や関数内でない）ステートメントは `$:` という [JS ラベル構文](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/label) のプレフィックスをつけることでリアクティブにできます。リアクティブステートメントは依存する値が変更されるたび、コンポーネント更新の
ステートメントで良いと思います。また、ドキュメントも日本語のほうにリンクを変更してくださりありがとうございます！

2021-02-12 05:39 UTC, tomoam commented on content/docs/ja/01-component-format.ja.md
> +		console.log(`現在のタイトルは ${title}`);
OKです、ありがとうございます！

2021-02-12 05:39 UTC, tomoam commented on content/docs/ja/01-component-format.ja.md
> +`$:` のブロック内に直接現れる値だけがリアクティブステートメントの依存関係になります。例えば次のコードで `total` は `x` が変更された時にのみ更新され、`y` では更新されません。
「次の」で良いと思います、翻訳もOKです！

below/following/...の使い分けについては何が正しいか私ではわかりません、すみませんw

2021-02-12 15:10 UTC, jay-es commented
@tomoam 見出し部分も翻訳いたしました。
ご確認よろしくお願いいたします:pray:

2021-02-13 04:30 UTC, tomoam approved these changes
翻訳OKです！ありがとうございました！

2021-02-13 04:31 UTC, merged