FAQ ja translation. Except 600
svelte-jp/svelte-site-jp pull request #268
Opened 2021-02-12 23:48 UTC by takoyaro

FAQは#600を除いて全て翻訳されていますが、これは `scale` を日本語に翻訳する方法がわからないからです。

2021-02-13 04:41 UTC, tomoam commented
レビューはまだ着手できていないのですが、お先に #270 になにかコメントをして頂けますか。
そうすると #270 のAssigneesに @takoyaro さんを割り当てることができるようになるので！

2021-02-13 05:48 UTC, myLifeAsaDog commented
@takoyaro 

`VueJS` だとそのまま `スケールする` になってますね、なので 「Does Svelte scale?」 なら

> Svelteはスケールしますか？ 

でも、それほど違和感はないと思います。

原語を重視せず、意訳で良いのであれば

> Svelteは大規模なアプリケーション開発にも耐えられますか？
Svelteは大規模開発も出来ますか？

という感じになると思います。

2021-02-13 06:23 UTC, tomoam requested changes
翻訳ありがとうございました！
日本語の意味がおかしいところはほとんどありませんでした、さすがですね！

スペースを消してもらったり丁寧な言い回しにしてもらったりする部分などがありましたので、修正をお願いします！

2021-02-13 06:23 UTC, tomoam commented on content/faq/ja/500-what-about-typescript-support.ja.md
> +タイプまたはインタフェースをインポートするには、[TypeScriptの`type`修飾子](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export):
末尾に`を使用します`を加えてください！

```
タイプまたはインタフェースをインポートするには、[TypeScriptの`type`修飾子](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export):
```
↓
```
タイプまたはインタフェースをインポートするには、[TypeScriptの`type`修飾子](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export)を使用します:
```

2021-02-13 06:23 UTC, tomoam commented on content/faq/ja/500-what-about-typescript-support.ja.md
> +`svelte-preprocess` はインポートが型であるか値であるかを認識しないため、 `type` 修飾子を使用する必要があります。 `svelte-preprocess` は他のファイルを認識することなく一度に1つのファイルのみをトランスポーズするため、この修飾子が存在しない型のみを含むインポートを安全に消去することはできません。
`トランスポーズ`を`トランスパイル`にしてください！

```
`svelte-preprocess` はインポートが型であるか値であるかを認識しないため、 `type` 修飾子を使用する必要があります。 `svelte-preprocess` は他のファイルを認識することなく一度に1つのファイルのみをトランスポーズするため、この修飾子が存在しない型のみを含むインポートを安全に消去することはできません。
```
↓
```
`svelte-preprocess` はインポートが型であるか値であるかを認識しないため、 `type` 修飾子を使用する必要があります。 `svelte-preprocess` は他のファイルを認識することなく一度に1つのファイルのみをトランスパイルするため、この修飾子が存在しない型のみを含むインポートを安全に消去することはできません。
```

2021-02-13 06:23 UTC, tomoam commented on content/faq/ja/800-how-do-i-test-svelte-apps.ja.md
> +ビューロジックとビジネスロジックを分離することをお勧めします。データ変換またはコンポーネント間の状態管理は、Svelteコンポーネントの外部に保管するのが最適です。このようにしてJavaScriptの機能をテストするのと同じように、これらの部分をテストすることができます。コンポーネントをテストする際には、コンポーネントのロジックをテストし、Svelteライブラリには独自のテストがあり、Svelt
完璧です！ですが、最後の文章(`コンポーネントをテストする際には...`)は長いため、日本語話者にとって読みやすいように下記のようにしてください。

```
コンポーネントをテストする際には、コンポーネントのロジックをテストし、Svelteライブラリには独自のテストがあり、Svelteが提供する実装の詳細をテストする必要はないことを覚えておくのが最善です。
```
↓
```
コンポーネントをテストする際には、コンポーネントのロジックはテストをして、Svelteが提供する実装の詳細はテストする必要はないことを覚えておくのがベストです(Svelteライブラリにはそれ自身のテストがあるため)。
```

2021-02-13 06:23 UTC, tomoam commented on content/faq/ja/800-how-do-i-test-svelte-apps.ja.md
> +テストを行うときにはいくつかの方法がありますが、一般的にはコンポーネントをコンパイルして何かにマウントし、テストを実行します。基本的には、テストするコンポーネントごとにバンドルを作成し(なぜなら、svelteはコンパイラであり、通常のライブラリではないからです。)、それらをマウントする必要があります。JSDOMインスタンスにマウントできます。また、Playwright、Puppeteer、Cyp
最後の文章(`また、Playwright...`)を下記のように変更してください。

```
また、Playwright、Puppeteer、Cypressなどのライブラリを備えた本物のブラウザを使うこともできる。
```
↓
```
また、Playwright、Puppeteer、Cypressなどのライブラリを使用して本物のブラウザを使うこともできます。
```

2021-02-13 06:23 UTC, tomoam commented on content/faq/ja/900-is-there-a-router.ja.md
> +公式なソリューションとしては、単なるルーティング・ライブラリーというものはありません。しかし、Svelte上に構築された、独自のファイルシステムベースのルーティングを含むNext.js形式のアプリケーションフレームワークである公式の [Sapper](https://sapper.svelte.dev/) フレームワークがある。
末尾を丁寧語にしてください！

```
しかし、Svelte上に構築された、独自のファイルシステムベースのルーティングを含むNext.js形式のアプリケーションフレームワークである公式の [Sapper](https://sapper.svelte.dev/) フレームワークがある。
```
↓
```
しかし、Svelte上に構築された、独自のファイルシステムベースのルーティングを含むNext.js形式のアプリケーションフレームワークである公式の [Sapper](https://sapper.svelte.dev/) フレームワークがあります。
```

2021-02-24 11:05 UTC, tomoam commented
@takoyaro 
せっかくほとんど翻訳できているで、今の段階でこれをマージしちゃいますね！
修正と600の翻訳については別のIssue/PRで実施することにしましょう！

2021-02-24 11:06 UTC, tomoam approved these changes

2021-02-24 11:10 UTC, takoyaro commented
時間がかかってすみません、東京出張が思ったより忙しいです...

2021-02-24 11:11 UTC, tomoam commented
大丈夫ですよ！むしろほとんど翻訳できているのに、今までマージしてなくてごめんなさい！

2021-02-24 11:12 UTC, merged