add 03-run-time svelte/animate in Japanese
svelte-jp/svelte-site-jp pull request #285
Opened 2021-02-14 08:31 UTC by myLifeAsaDog

close #248

2021-02-14 12:12 UTC, tomoam requested changes

2021-02-14 12:12 UTC, tomoam commented on content/docs/ja/03-run-time.ja.md
> +`flip` 関数は要素の開始位置と終了位置を計算し、その間で `x` と `y` の値を変換してアニメーションを行います。`flip` は [First, Last, Invert, Invert, Play] の略です(https://aerotwist.com/blog/flip-your-animations/)。
`Invert`が2つ書かれているので1つ消してください！

2021-02-14 12:32 UTC, myLifeAsaDog commented on content/docs/ja/03-run-time.ja.md
> +`flip` 関数は要素の開始位置と終了位置を計算し、その間で `x` と `y` の値を変換してアニメーションを行います。`flip` は [First, Last, Invert, Invert, Play] の略です(https://aerotwist.com/blog/flip-your-animations/)。
すいません、修正しました！

2021-02-15 00:24 UTC, tomoam commented on content/docs/ja/03-run-time.ja.md
> +`flip` 関数は要素の開始位置と終了位置を計算し、その間で `x` と `y` の値を変換してアニメーションを行います。`flip` は [First, Last, Invert, Invert, Play] の略です(https://aerotwist.com/blog/flip-your-animations/)。
大丈夫です！OKです！

2021-02-15 00:25 UTC, tomoam approved these changes
ありがとうございます、OKです！

2021-02-15 00:25 UTC, merged