add 02-template-syntax Element directives animate:fn Custom animation…
svelte-jp/svelte-site-jp pull request #308
Opened 2021-02-15 14:36 UTC by myLifeAsaDog

close #223

2021-02-15 14:37 UTC, myLifeAsaDog commented on content/docs/ja/02-template-syntax.ja.md
> +アニメーションは、`node`、`animation` オブジェクト、および任意の `paramaters` を引数として指定するカスタム関数を使用することができます。`animation` パラメータは、`from` と `to` プロパティを含むオブジェクトで、それぞれ要素の `start` と `end` の位置におけるジオメトリを記述した [DOMRect](https://develo
> ジオメトリ

これはどうしようもなかったのでそのままカタカナにしてます。

2021-02-15 22:25 UTC, tomoam requested changes

2021-02-15 22:25 UTC, tomoam commented on content/docs/ja/02-template-syntax.ja.md
このあたりで行数が２行減っているようです、申し訳ありませんが修正をお願いします、すみません！

2021-02-16 00:40 UTC, tomoam commented on content/docs/ja/02-template-syntax.ja.md
> +アニメーションは、`node`、`animation` オブジェクト、および任意の `paramaters` を引数として指定するカスタム関数を使用することができます。`animation` パラメータは、`from` と `to` プロパティを含むオブジェクトで、それぞれ要素の `start` と `end` の位置におけるジオメトリを記述した [DOMRect](https://develo
了解です、これは`ジオメトリ`でで良いと思います！

2021-02-16 03:08 UTC, myLifeAsaDog commented on content/docs/ja/02-template-syntax.ja.md
すいません調整しました！

2021-02-16 14:47 UTC, tomoam commented on content/docs/ja/02-template-syntax.ja.md
ありがとうございます！

2021-02-16 14:48 UTC, tomoam approved these changes
OKです、ありがとうございます！

2021-02-16 14:48 UTC, merged