add rethinking reactivity in Japanese
svelte-jp/svelte-site-jp pull request #346
Opened 2021-02-28 11:45 UTC by myLifeAsaDog

2021-02-28 12:24 UTC, myLifeAsaDog commented on content/blog/ja/2019-04-22-svelte-3-rethinking-reactivity.ja.md
> -After several months of being just days away, we are over the moon to announce the stable release of Svelte 3. This is a huge release representing hundreds of hours of work by many people in the Svel
はじめて知ったんですけど

> I'm so over the moon!

で「（月までジャンプしちゃうくらい）めちゃくちゃ嬉しい！」という意味だそうです。

2021-02-28 12:52 UTC, myLifeAsaDog commented on content/blog/ja/2019-04-22-svelte-3-rethinking-reactivity.ja.md
>  	<p>In fact, Svelte 3 is basically <a href="https://twitter.com/threepointone/status/1057179801109311488">Sunil's fault</a>.</p>
ここ参照先を見ても Snil という人が見つけられなくて、イマイチ意味が伝わってこないので、そのままにしてます。

2021-02-28 12:53 UTC, myLifeAsaDog commented on content/blog/ja/2019-04-22-svelte-3-rethinking-reactivity.ja.md
> +コンパイラなので、裏でアサインメントをインストルメントすることで、それが可能になります。
> アサインメントをインストルメントする

これをなんとかしたい

2021-02-28 12:55 UTC, myLifeAsaDog commented on content/blog/ja/2019-04-22-svelte-3-rethinking-reactivity.ja.md
> +また、私たちはキャッチフレーズを「魔法のように消える UI フレームワーク」から「サイバネティックに強化されたウェブアプリ」に変更しました。Svelte には様々な側面があります。-- 卓越した性能、小さなバンドル、アクセシビリティ、組み込みのスタイルカプセル化、宣言的な遷移、使いやすさ、コンパイラであることなど -- その中のどれか一つに焦点を当てることは、他のものに不公平感を与えるような気が
ちなみにウィリアム・ギブソンはサイバーパンクの嚆矢である「ニューロマンサー」の著者なんですけど、それって一般常識なのかよくわからないすね。

2021-03-01 13:01 UTC, tomoam commented on content/blog/ja/2019-04-22-svelte-3-rethinking-reactivity.ja.md
>  	<p>In fact, Svelte 3 is basically <a href="https://twitter.com/threepointone/status/1057179801109311488">Sunil's fault</a>.</p>
こちらはそのままで良いと思います。

Sunilさんはこのtweetをした[@threepointone](https://twitter.com/threepointone)さんのようです。
twitterから辿るとご本人の[ホームページ](https://www.coolcomputerclub.com/about/)があります。

この66行目のtweetはおそらくこのSunilさんが誤ってRich Harrisさんにメンションしたのだと思います。
しかしそれがたまたまVueの作者のEvan Youさんが hooks のAPIに対して迷っているようなtweetで、それがhooksのようなアプローチをやめるきっかけになったようですね。

2021-03-01 13:02 UTC, tomoam commented on content/blog/ja/2019-04-22-svelte-3-rethinking-reactivity.ja.md
> -After several months of being just days away, we are over the moon to announce the stable release of Svelte 3. This is a huge release representing hundreds of hours of work by many people in the Svel
大変勉強になります！

2021-03-01 13:08 UTC, tomoam commented on content/blog/ja/2019-04-22-svelte-3-rethinking-reactivity.ja.md
> +コンパイラなので、裏でアサインメントをインストルメントすることで、それが可能になります。
良さそうなのを見つけました！

このページの真ん中あたりにある「マイクロソフト用語集での「instrument」の意味」で、
https://ejje.weblio.jp/content/instrument

> To tag the source code in order to measure the amount of time spent in each area.

と記載があります。
なのでこの部分の翻訳は、`裏で代入にタグ付けすることで、それが可能になります。` のような感じでどうでしょうか。

2021-03-01 13:10 UTC, tomoam commented on content/blog/ja/2019-04-22-svelte-3-rethinking-reactivity.ja.md
> +また、私たちはキャッチフレーズを「魔法のように消える UI フレームワーク」から「サイバネティックに強化されたウェブアプリ」に変更しました。Svelte には様々な側面があります。-- 卓越した性能、小さなバンドル、アクセシビリティ、組み込みのスタイルカプセル化、宣言的な遷移、使いやすさ、コンパイラであることなど -- その中のどれか一つに焦点を当てることは、他のものに不公平感を与えるような気が
Rich Harrisさんは元々エンジニアではなく記者だったそうなので、文章も教養で溢れている印象を受けますね。

2021-03-01 13:16 UTC, tomoam requested changes
レビューが遅れてすみません、ほとんどOKです、ありがとうございます！
一部修正頂きたいところがありましたので、ご対応お願いします！

2021-03-01 13:16 UTC, tomoam commented on content/blog/ja/2019-04-22-svelte-3-rethinking-reactivity.ja.md
> +改修されているのはコンポーネントだけではありません。[svelte.technology](https://svelte.technology) から [svelte.dev](https://svelte.dev) に移行した新しいロゴとウェブサイトを作成したAchimVedamの素晴らしいデザイン作業のおかげで、Svelte自体はまったく新しいルックアンドフィールになっています。
`AchimVedam` の部分、リンクがなくなっているので戻しましょう！

2021-03-01 13:16 UTC, tomoam commented on content/blog/ja/2019-04-22-svelte-3-rethinking-reactivity.ja.md
> +このリリースは大変なものでしたが、まだ完成には至っていません。 よりスマートでコンパクトなコードと長い機能のウィッシュリストを生成するためのアイデアがたくさんあります。
多分104行目もこの行にくるはずなので、改行を調整して頂けますでしょうか。

2021-03-01 13:35 UTC, myLifeAsaDog commented on content/blog/ja/2019-04-22-svelte-3-rethinking-reactivity.ja.md
> +コンパイラなので、裏でアサインメントをインストルメントすることで、それが可能になります。
修正してみましたー

2021-03-01 13:36 UTC, myLifeAsaDog commented on content/blog/ja/2019-04-22-svelte-3-rethinking-reactivity.ja.md
> +このリリースは大変なものでしたが、まだ完成には至っていません。 よりスマートでコンパクトなコードと長い機能のウィッシュリストを生成するためのアイデアがたくさんあります。
すいません後でなおそうと思って忘れていたので修正しましたー

2021-03-01 13:36 UTC, myLifeAsaDog commented on content/blog/ja/2019-04-22-svelte-3-rethinking-reactivity.ja.md
> +改修されているのはコンポーネントだけではありません。[svelte.technology](https://svelte.technology) から [svelte.dev](https://svelte.dev) に移行した新しいロゴとウェブサイトを作成したAchimVedamの素晴らしいデザイン作業のおかげで、Svelte自体はまったく新しいルックアンドフィールになっています。
修正しました！

2021-03-01 13:57 UTC, tomoam approved these changes
OKです、長文の翻訳ありがとうございました！
とても助かります！

2021-03-01 13:57 UTC, merged