translate: blog of the-easiest-way-to-get-started in Japanese
svelte-jp/svelte-site-jp pull request #353
Opened 2021-03-07 15:13 UTC by kkeeth

## overview

`The easiest way to get started with Svelte` を日本語に翻訳しました。

## isseus
close #333 

## note
多少意訳も混ざっておりますので、ご注意ください。違和感等ございましたら遠慮なくご指摘いただけると助かりますー。

2021-03-08 14:27 UTC, tomoam requested changes
レビューが遅れて申し訳ありません。
一点だけ、修正というより追記して頂きたいことがございますのでお願いします！

2021-03-08 14:27 UTC, tomoam commented on content/blog/ja/2017-08-07-the-easiest-way-to-get-started.ja.md
このURLを参考に、6行目のすぐあとに日本語翻訳であることを示すメッセージを入れて頂けますか。
https://github.com/svelte-jp/svelte-site-jp/pull/346/files#diff-7983ece1e5bfde4e73045d87d78de41d9f85f1344a8941fa3f5894df870fbc8fR7-R13

2021-03-10 14:16 UTC, kkeeth commented on content/blog/ja/2017-08-07-the-easiest-way-to-get-started.ja.md
追加しました！ https://github.com/svelte-jp/svelte-site-jp/pull/353/commits/cdfcea281b937109db661da7641b0b10c9f611e1

2021-03-11 10:52 UTC, tomoam approved these changes
OKです、翻訳ありがとうございました！とても助かります！

2021-03-11 10:52 UTC, merged