translate contents of update v3.37.0 into Japanese
svelte-jp/svelte-site-jp pull request #407
Opened 2021-04-18 13:38 UTC by jay-es

https://github.com/svelte-jp/svelte-site-jp/pull/368/files#diff-24f9368efc3a14bc1397a826edf88b14bbdb6a1b91a7a96d04368da785323774
で追加された箇所の翻訳です。よろしくお願いします。

close #401

2021-04-18 23:50 UTC, tomoam requested changes
翻訳ありがとうございます！
お手数ですが、修正して頂きたい箇所がございますので、ご対応をお願いできますか。

2021-04-18 23:50 UTC, tomoam commented on content/docs/ja/03-run-time.ja.md
> +| オプション | デフォルト | 説明 |
この `オプション` を `パラメータ` に変更していただけますか

2021-04-18 23:50 UTC, tomoam commented on content/docs/ja/03-run-time.ja.md
> +| `props` | `{}` | 	コンポーネントに渡すプロパティのオブジェクト
`コンポーネントに渡すプロパティのオブジェクト` の直前に Tab が入っているようですので、削除していただけますか

2021-04-19 11:15 UTC, jay-es commented
コピペの際に確認がもれていました:bow:
ご確認よろしくお願いいたします。

2021-04-20 01:04 UTC, tomoam approved these changes
OKです！ご対応ありがとうございました！
いつもいつもありがとうございます！

2021-04-20 01:05 UTC, merged