[Blog]What's new in Svelte: August 2021 の翻訳
svelte-jp/svelte-site-jp pull request #484
Opened 2021-09-11 03:15 UTC by yamanoku

close #482

2021-09-12 13:54 UTC, tomoam requested changes
迅速なご対応ありがとうございます！1点だけ修正お願いします！

2021-09-12 13:54 UTC, tomoam commented on content/blog/ja/2021-08-01-whats-new-in-svelte-august-2021.ja.md
> +[#6416](https://github.com/sveltejs/svelte/pull/6416)）。
ここに改行が入ってしまっているようですので、削除して頂けますでしょうか。

2021-09-12 22:59 UTC, yamanoku commented
@tomoam レビューありがとうございます！対応いたしました 👍🏼

2021-09-13 00:02 UTC, tomoam commented
ご対応ありがとうございます、マージさせていただきます！

2021-09-13 00:03 UTC, merged