#492を翻訳しました！
svelte-jp/svelte-site-jp pull request #498
Opened 2021-11-15 01:00 UTC by nullnyat

2021-11-15 01:06 UTC, nullnyat commented
google翻訳に頼りつつなるべく違和感がないように翻訳しました．
やり方がこれで正しいかわからないので間違っていたらすみません．

2021-11-15 10:31 UTC, tomoam requested changes
長文ですのでとても大変だったと思います、ご対応ありがとうございました！

いくつか修正して頂きたい箇所がございますので、お手数ですが修正をお願いいたします！

2021-11-15 10:43 UTC, tomoam commented on site/content/blog/2021-11-01-whats-new-in-svelte-november-2021.md
> +SvelteKitが[80%完了マーク](https://github.com/sveltejs/kit/milestone/2)を超え、GitHubで[5000スター](https://github.com/sveltejs/kit)を超え、Sapperよりも多くの利用者がいる現在、SvelteKitを試すのに最適な時期はありません。コミュニティの多くの人が試しているので、今月はかなり大きなシ
> SvelteKitが80%完了マークを超え

この部分の「mark」は、記録とか位置とか到達点ということを意味しています。
なのでここはこのような和訳にすると良いでしょう。

```markdown
SvelteKitの完成度が[80%を超え](https://github.com/sveltejs/kit/milestone/2)、
```

2021-11-15 23:50 UTC, tomoam commented
OKです、ご対応ありがとうございました！

2021-11-15 23:51 UTC, merged

2021-11-16 03:58 UTC, nullnyat commented
こちらこそ丁寧に色々教えてくださりありがとうございます！！